### ISSUE TITLE
[Need Answer]

### ISSUE THREAD

**Issue by 321paranoiawhy** [sodiray/radash#425]
Giving the code like this:

```ts
import {tryit} from 'radash';

const str1 = '[1,2,3]';
const str2 = null;

const [err1, data1] = tryit(JSON.parse)(str1);
const [err2, data2] = tryit(JSON.parse)(str2);
```

`TS` gives the error `TS2488: Type
[Error, undefined] | [undefined, any] | Promise<[Error, undefined] | [undefined, any]>
must have a [Symbol.iterator]() method that returns an iterator.`, how can we solve this? Or maybe I have wrong usage in `tryit`?

**Comment by MarlonPassos-git** [comment]
If you are discussing the line:
```ts
const [err2, data2] = tryit(JSON.parse)(str2);
``` 
The error occurs because JSON.parse does not allow null values.

**Comment by MarlonPassos-git** [comment]
`tryit` is an async function, to work you need to use the `await`
![image](https://github.com/user-attachments/assets/df2b3a5e-ec4c-4cea-8bbd-f2280452d35c)

**Comment by 321paranoiawhy** [comment]
> `tryit` is an async function, to work you need to use the `await` ![image](https://private-user-images.githubusercontent.com/63638196/365400932-df2b3a5e-ec4c-4cea-8bbd-f2280452d35c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4OTQ3MDUsIm5iZiI6MTcyNTg5NDQwNSwicGF0aCI6Ii82MzYzODE5Ni8zNjU0MDA5MzItZGYyYjNhNWUtZWM0Yy00Y2VhLThiYmQtZjIyODA0NTJkMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE1MDY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YjZmYzM4MGE4ZGI3NjBjNjVjYWY5MGEyMWNjZjI2MzljOWJlZGExYzI5YTExMWM5OGUyZWJmOWIyY2M0ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9MN9f5blHT_NPCWR8qumE-wOVS_VG7CrwVYKCix-NUw)

THX!
