### ISSUE TITLE
Why not use Number.isInteger

### ISSUE THREAD

**Issue by JonZhang3** [sodiray/radash#427]
Why not just use `Number.isInteger` here?
https://github.com/sodiray/radash/blob/069b26cdd7d62e6ac16a0ad3baa1c9abcca420bc/src/typed.ts#L35

**Comment by MarlonPassos-git** [comment]
JonZhang3 I think it's about the type inference. When use only `Number.isInteger` has not type inference. 

![image](https://github.com/user-attachments/assets/cf8bb861-426f-4962-a394-ceea07232cca)

**Comment by MarlonPassos-git** [comment]
But about the implementation, it might make sense to use the Number.isInteger. 

https://github.com/sodiray/radash/blob/069b26cdd7d62e6ac16a0ad3baa1c9abcca420bc/src/typed.ts#L36

**Comment by aleclarson** [comment]
[Radashi](https://github.com/radashi-org/radashi) (a maintained fork of Radash) already uses `Number.isInteger` for its `isInt` function.

See here: https://github.com/radashi-org/radashi/blob/main/src/typed/isInt.ts

(Note that the `(() => …)()` function is for tree-shaking, and it gets removed when your code is minified.)

**Comment by JonZhang3** [comment]
> JonZhang3 I think it's about the type inference. When use only `Number.isInteger` has not type inference.
> 
> ![image](https://private-user-images.githubusercontent.com/63638196/365413651-cf8bb861-426f-4962-a394-ceea07232cca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTI1MjMsIm5iZiI6MTcyNTg1MjIyMywicGF0aCI6Ii82MzYzODE5Ni8zNjU0MTM2NTEtY2Y4YmI4NjEtNDI2Zi00OTYyLWEzOTQtY2VlYTA3MjMyY2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAzMjM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYzA2YWVhYjcyZjg5NTFiZDMwZGU4YTQ2ZjhmMjYwYTIyMzdkMjdiOTY5ZGI1NTkyODE2NzRhZDA2YzZmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xIOq_DpWyZeKgCaJ7lTisyW6eZ-ExdMf3vq2AYw9SY0)

That's really something I hadn't thought of, thanks for the tip!
